# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[conda]
disabled = true

[crystal]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[nix_shell]
disabled = true

[php]
disabled = true

[singularity]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[golang]
disabled = true

[rust]
disabled = true

[buf]
disabled = true

[git_metrics]
disabled = true

[terraform]
disabled = true

#####################
[character]
success_symbol = "[ÔêÆ](bold green)"
error_symbol = "[Ôëß](bold red)"

[time]
disabled = false
format = "at [$time]($style) "

[container]
symbol = ""
style = "bold black dimmed"
format = '[$name]($style) '

[git_state]
disabled = false

[kubernetes]
disabled = false
symbol = ""
style = "bold blue"
format = '[k8s $symbol$context(\($namespace\))]($style) in '

[package]
disabled = false
symbol = "Ô£ñ "
format = "[$symbol$version]($style) "

[aws]
disabled = false
symbol = "aws [$region]($style)"

[gcloud]
disabled = false
format = 'gcp [$project]($style) '

[azure]
disabled = false
format = 'azure [$subscription]($style) '

[git_branch]
disabled = false
symbol = "git "

[git_commit]
disabled = true
commit_hash_length = 7
tag_symbol = "üîñ "
tag_disabled = false
only_detached = false
